In [1]:
import pandas as pd
import numpy as np

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# "conda install scikit-learn"을 통해 다운로드
# 예측 결과가 문자열 형태인데 이것을 숫자 형태로 바꾸어주는 라이브러리
from sklearn.preprocessing import LabelEncoder

In [2]:
np.random.seed(3)
tf.random.set_seed(3)

# 칼럼이 0, 1, 2, 3, 4, 5 ... 57, 58, 59, 60
df = pd.read_csv('deeplearning/dataset/sonar.csv', header=None)
df.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  
3  0.0040  0.0117   R  
4  0.0107  0.0094   R  

[5 rows x 61 columns]

In [3]:
dataset = df.values
dataset

array([[0.02, 0.0371, 0.0428, ..., 0.009, 0.0032, 'R'],
       [0.0453, 0.0523, 0.0843, ..., 0.0052, 0.0044, 'R'],
       [0.0262, 0.0582, 0.1099, ..., 0.0095, 0.0078, 'R'],
       ...,
       [0.0522, 0.0437, 0.018, ..., 0.0077, 0.0031, 'M'],
       [0.0303, 0.0353, 0.049, ..., 0.0036, 0.0048, 'M'],
       [0.026, 0.0363, 0.0136, ..., 0.0061, 0.0115, 'M']], dtype=object)

In [4]:
# dataset의 마지막 항목인 'R', 'M'과 같은 문자열 데이터를 제외하고 실수 형태로 전환

dataset[:, :-1] = dataset[:, :-1].astype(float)
dataset

array([[0.02, 0.0371, 0.0428, ..., 0.009, 0.0032, 'R'],
       [0.0453, 0.0523, 0.0843, ..., 0.0052, 0.0044, 'R'],
       [0.0262, 0.0582, 0.1099, ..., 0.0095, 0.0078, 'R'],
       ...,
       [0.0522, 0.0437, 0.018, ..., 0.0077, 0.0031, 'M'],
       [0.0303, 0.0353, 0.049, ..., 0.0036, 0.0048, 'M'],
       [0.026, 0.0363, 0.0136, ..., 0.0061, 0.0115, 'M']], dtype=object)

In [5]:
x = dataset[:, :60]
y_obj = dataset[:, 60]
y_obj

array(['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M

In [6]:
e = LabelEncoder()
e.fit(y_obj)
y = e.transform(y_obj)
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
model = Sequential()
model.add(Dense(24, input_dim = 60, activation = 'relu'))
model.add(Dense(10, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

In [15]:
# optimizer : 빠르고 효율적으로 알고리즘을 수행하기 위해 사용하는 방식
# metrics : 평가 기준 설정

model.compile(loss = 'binary_crossentropy',
             optimizer='adam',
             metrics = ['accuracy']
             )

model.fit(x.astype(float), y, epochs=500, batch_size=5, verbose = False)
model.fit(x.astype(float), y, epochs=5, batch_size=1)

Epoch 1/5
208/208 [==============================] - 0s 1ms/step - loss: 0.1810 - accuracy: 0.9808
Epoch 2/5
208/208 [==============================] - 0s 1ms/step - loss: 0.6968 - accuracy: 0.9231
Epoch 3/5
208/208 [==============================] - 0s 1ms/step - loss: 0.0052 - accuracy: 0.9952
Epoch 4/5
208/208 [==============================] - 0s 1ms/step - loss: 0.0737 - accuracy: 0.9760
Epoch 5/5
208/208 [==============================] - 0s 1ms/step - loss: 2.7571e-04 - accuracy: 1.0000


In [9]:
accuracy = model.evaluate(x.astype(float), y)
print('\nAccuracy : %.4f' % accuracy[1]) # [0]은 손실률을 의미

7/7 [==============================] - 0s 856us/step - loss: 0.0124 - accuracy: 1.0000

Accuracy : 1.0000


In [10]:
# -------------------------------------------------------------------------

# 학습셋과 데이터셋을 구분하여 학습시키기

In [11]:
from sklearn.model_selection import train_test_split

np.random.seed(3)
tf.random.set_seed(3)

# 칼럼이 0, 1, 2, 3, 4, 5 ... 57, 58, 59, 60
df = pd.read_csv('deeplearning/dataset/sonar.csv', header=None)

dataset = df.values

# dataset의 마지막 항목인 'R', 'M'과 같은 문자열 데이터를 제외하고 실수 형태로 전환
dataset[:, :-1] = dataset[:, :-1].astype(float)

x = dataset[:, :60]
y_obj = dataset[:, 60]

e = LabelEncoder()
e.fit(y_obj)
y = e.transform(y_obj)

In [12]:
#  train_test_split() : 데이터를 학습과 테스트용의 두 그룹으로 나누어주는 함수
# 학습셋을 70%, 테스트셋을 30%로 설정, 랜덤 테이블은 0번으로 고정

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

In [13]:
model = Sequential()
model.add(Dense(24, input_dim = 60, activation = 'relu'))
model.add(Dense(10, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

# optimizer : 빠르고 효율적으로 알고리즘을 수행하기 위해 사용하는 방식
# metrics : 평가 기준 설정

model.compile(loss = 'binary_crossentropy',
             optimizer='adam',
             metrics = ['accuracy']
             )

model.fit(x_train.astype(float), y_train, epochs=200, batch_size=5, verbose = False)
model.fit(x_train.astype(float), y_train, epochs=5, batch_size=1)

Epoch 1/5
145/145 [==============================] - 0s 1ms/step - loss: 0.3884 - accuracy: 0.9241
Epoch 2/5
145/145 [==============================] - 0s 1ms/step - loss: 0.0889 - accuracy: 0.9586
Epoch 3/5
145/145 [==============================] - 0s 1ms/step - loss: 0.0294 - accuracy: 0.9793
Epoch 4/5
145/145 [==============================] - 0s 1ms/step - loss: 0.0077 - accuracy: 1.0000
Epoch 5/5
145/145 [==============================] - 0s 1ms/step - loss: 0.0044 - accuracy: 1.0000


In [14]:
accuracy = model.evaluate(x_test.astype(float), y_test)
print('\nAccuracy : %.4f' % accuracy[1])

2/2 [==============================] - 0s 811us/step - loss: 0.8593 - accuracy: 0.8413

Accuracy : 0.8413
