In [3]:
import pandas as pd
import numpy as np

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# "conda install scikit-learn"을 통해 다운로드
# 문자열 형태의 예측 결과를 숫자 형태로 바꾸어주는 라이브러리
from sklearn.preprocessing import LabelEncoder

from sklearn.model_selection import StratifiedKFold

In [5]:
np.random.seed(0)
tf.random.set_seed(0)

df = pd.read_csv('deeplearning/dataset/sonar.csv', header=None)
df.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  
3  0.0040  0.0117   R  
4  0.0107  0.0094   R  

[5 rows x 61 columns]

In [6]:
dataset = df.values
x = dataset[:, :60]
y_obj = dataset[:, 60]

e = LabelEncoder()
e.fit(y_obj)
y = e.transform(y_obj)

In [13]:
# k겹 교차 검증
# 10개의 파일로 쪼갤 것

n_fold = 10
skf = StratifiedKFold(n_splits=n_fold, shuffle=True, random_state=0)
skf # 학습셋과 테스트셋의 묶음이 들어가 있음

StratifiedKFold(n_splits=10, random_state=0, shuffle=True)

In [29]:
# sonor.csv 파일은 207행의 데이터로 이우러져 있는데,
# 그 중 학습셋으로 이용될 데이터의 행과
# 테스트셋으로 이용될 행이 구분되어 출력

for train, test in skf.split(x, y):
    print(train)
    print(test)
    print('_' * 120)

[  0   1   3   4   5   6   7   8   9  10  11  12  13  15  16  17  18  20
  21  23  24  25  27  28  29  30  31  32  33  34  35  36  37  38  39  41
  42  43  45  46  47  48  50  51  53  54  55  56  57  58  59  60  61  62
  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80
  81  82  83  84  85  86  87  88  89  90  92  93  94  95  96  97  98  99
 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 118 120
 121 123 124 125 126 127 129 130 131 132 133 134 135 136 137 138 139 140
 142 143 144 145 146 147 148 149 150 152 153 154 155 156 157 158 159 160
 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178
 179 180 181 182 183 184 185 186 187 188 189 190 192 193 194 195 198 199
 200 201 202 203 205 206 207]
[  2  14  19  22  26  40  44  49  52  91 100 117 119 122 128 141 151 191
 196 197 204]
________________________________________________________________________________________________________________________
[  0   1   2   3   4   5   7   8

In [31]:
for train, test in skf.split(x, y):
    print(x[train])
    print(x[test])
    print('_' * 120)

[[0.02 0.0371 0.0428 ... 0.0084 0.009 0.0032]
 [0.0453 0.0523 0.0843 ... 0.0049 0.0052 0.0044]
 [0.01 0.0171 0.0623 ... 0.0044 0.004 0.0117]
 ...
 [0.0522 0.0437 0.018 ... 0.0138 0.0077 0.0031]
 [0.0303 0.0353 0.049 ... 0.0079 0.0036 0.0048]
 [0.026 0.0363 0.0136 ... 0.0036 0.0061 0.0115]]
[[0.0262 0.0582 0.1099 ... 0.0164 0.0095 0.0078]
 [0.0124 0.0433 0.0604 ... 0.0196 0.0147 0.0062]
 [0.0126 0.0149 0.0641 ... 0.0094 0.0116 0.0063]
 ...
 [0.005 0.0017 0.027 ... 0.0063 0.0017 0.0028]
 [0.0366 0.0421 0.0504 ... 0.0017 0.0027 0.0027]
 [0.0323 0.0101 0.0298 ... 0.0032 0.0062 0.0067]]
________________________________________________________________________________________________________________________
[[0.02 0.0371 0.0428 ... 0.0084 0.009 0.0032]
 [0.0453 0.0523 0.0843 ... 0.0049 0.0052 0.0044]
 [0.0262 0.0582 0.1099 ... 0.0164 0.0095 0.0078]
 ...
 [0.0522 0.0437 0.018 ... 0.0138 0.0077 0.0031]
 [0.0303 0.0353 0.049 ... 0.0079 0.0036 0.0048]
 [0.026 0.0363 0.0136 ... 0.0036 0.0061 0.011

In [32]:
accuracy = []

for train, test in skf.split(x, y):
    model = Sequential()
    model.add(Dense(24, input_dim = 60, activation = 'relu'))
    model.add(Dense(10, activation = 'relu'))
    model.add(Dense(1, activation = 'sigmoid'))
    
    model.compile(loss = 'binary_crossentropy',
             optimizer='adam',
             metrics = ['accuracy']
                 )
    
    model.fit(x[train].astype(float), y[train], epochs=30, batch_size=5, verbose = False)
    model.fit(x[train].astype(float), y[train], epochs=1, batch_size=1)
    
    k_accuracy = model.evaluate(x[test].astype(float), y[test])[1]
    accuracy.append(k_accuracy)

print()
print(f'{n_fold} fold accuracy : {accuracy}')

188/188 [==============================] - 0s 958us/step - loss: 0.3932 - accuracy: 0.8245


1/1 [==============================] - 0s 2ms/step - loss: 0.4522 - accuracy: 0.7000

10 fold accuracy : [0.761904776096344, 0.8571428656578064, 0.9047619104385376, 0.8095238208770752, 0.761904776096344, 0.8095238208770752, 0.7142857313156128, 0.761904776096344, 0.75, 0.699999988079071]
